data_collection_task:
  description: >
    收集B站上关于{topic}的以下数据：
    1 视频列表数据：
    视频地址、播放量、评论数、视频时长、视频标题、UP主昵称、UP主主页链接、视频发布日期
    2 视频详情页数据
    单条视频内容总结、点赞数、投币数、收藏数、转发数、弹幕数、弹幕内容、评论内容
    3 视频弹幕数据：
    单挑视频弹幕的内容、发布日期、发布时间、关联的视频标题
  expected_output: >
    数据结果产生3张csv格式的表格，分别对应视频列表数据、视频详情数据、视频弹幕数据
  agent: data_crawling_engineer

analyst_task:
  description: >
    分析 data_collection_task 产生的数据，并生成一份报告。
  expected_output: >
    这份报告包含以下内容：
    1 工作流的内容主要有哪些主题？各自的占比是多少？主题的意思是 像绘图工作流、小红书图文制作工作流、视频制作工作流、日报、周报工作流等这些内容。
    2 主要使用了哪些工具、框架，比如coze、n8n、dify、langchain这些，各自占比多少？
    3 从评论看，用户最需要哪些材料，更希望看到哪些内容？
    4 从弹幕内容看。用户更喜欢哪些内容？
  agent: data_analyst

competitive_account_production_task:
  description: >
    根据 data_collection_task 获取的数据，及以下账号A的信息，来完成任务。
    账号A的信息如下：
    定位：分享AI工作流 提高我们的工作效率
    主要的产品/服务：工作流框架（输出PDF/Xmind）、工作流讲解（视频内容）、工作流代码（Python代码）
    期望用户群：产品、运营、销售、创业者等想使用AI提高工作效率的人 
    账号内容解决的问题是：1 使用大模型、Agent处理部分工作，解放我们的双手，提高效率。  2 将部分工作SOP化，即尽量少做重复性工作，来提高效率。
    给出3个账号A最值得关注的竞争对手账号。并给出理由说明为什么是这些账号。
    给出3个账号A最值得关注的视频。并给出理由说明为什么是这些视频。
  expected_output: >
    一份报告，300字以内，包含以下内容：
    3个账号A最值得关注的竞争对手账号，需要有账号昵称、UP主页地址、以及理由。
    3个账号A最值得关注的视频，需要有视频标题、地址、以及理由。
  agent: data_analyst
  context:
    - data_collection_task